---
- name: update web servers
  hosts: n1
  become: yes

  tasks:
  - name: Ensure Git Installed
    yum:
      name: git
      state: installed

  - name: Ensure mynthra updated
    git:
      repo: https://github.com/ravi2krishna/ecomm.git
      dest: /var/www/html

...
