---
- name: update web servers
  hosts: n1
  become: yes

  tasks:   
  - name: copy config file
    copy:
       src: httpd.conf
       dest: /etc/httpd/conf/httpd.conf 

  - name: restart apache
    service:
       name: httpd
       state: restarted

...
